apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: ${ trigger['user'] }_App
  namespace: ${ trigger['user'] } 
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${ trigger['user'] }_App
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${ trigger['user'] }_App
    spec:
      containers:
        - image: 'docker.io/opsmx11/restapp:simple-1.0'
          imagePullPolicy: Always 
          name: restapp 
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9090
              name: prometheus
              protocol: TCP
